name: Build and upload Artifact
on:
  workflow_dispatch:
  # push:

jobs: 
  build:
    name: Build
    runs-on: macos-latest

    steps:

      - uses: actions/checkout@v4
        with:
          submodules: true

      - uses: waruhachi/theos-action@v2.4.6
        with:
          theos-src: 'theos/theos'
          theos-branch: 'master'
          sdks-src: 'theos/sdks'
          sdks-branch: 'master'
          libgcuniversal: true
          libgcuniversal-src: 'MrGcGamer/LibGcUniversalDocumentation'
          libgcuniversal-branch: 'master'
          altlist: true
          altlist-src: 'opa334/AltList'
          altlist-branch: 'main'
          
      - name: Install dependencies
        run: |
          brew update
          brew install libarchive
          
      - name: Build
        run: |
          cd ${{ github.workspace }}
          make
          echo "Folder struct:"
          ls
